# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{amaze_sns}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chee Yeo", "29 Steps UK"]
  s.date = %q{2011-07-28}
  s.description = %q{Ruby gem to interface with the Amazon Simple Notification Service}
  s.email = %q{info@29steps.co.uk}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/amaze/exceptions.rb",
     "lib/amaze/helpers.rb",
     "lib/amaze/request.rb",
     "lib/amaze/subscription.rb",
     "lib/amaze/topic.rb",
     "lib/amaze_sns.rb"
  ]
  s.homepage = %q{http://29steps.co.uk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.6")
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Ruby gem for Amazon Simple Notification Service SNS}
  s.test_files = [
    "spec/amaze_sns_spec.rb",
     "spec/em_http_request_spec_helper.rb",
     "spec/request_spec.rb",
     "spec/spec_helper.rb",
     "spec/subscription_spec.rb",
     "spec/topic_spec.rb",
     "spec/spec.opts"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_runtime_dependency(%q<em-http-request>, [">= 0.2.8"])
      s.add_runtime_dependency(%q<crack>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0.4.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.6.0.pre"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
      s.add_dependency(%q<em-http-request>, [">= 0.2.8"])
      s.add_dependency(%q<crack>, [">= 0.1.6"])
      s.add_dependency(%q<ruby-hmac>, [">= 0.4.0"])
      s.add_dependency(%q<json>, [">= 1.4.3"])
      s.add_dependency(%q<rspec>, [">= 2.0"])
      s.add_dependency(%q<webmock>, ["~> 1.6.0.pre"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.10"])
    s.add_dependency(%q<em-http-request>, [">= 0.2.8"])
    s.add_dependency(%q<crack>, [">= 0.1.6"])
    s.add_dependency(%q<ruby-hmac>, [">= 0.4.0"])
    s.add_dependency(%q<json>, [">= 1.4.3"])
    s.add_dependency(%q<rspec>, [">= 2.0"])
    s.add_dependency(%q<webmock>, ["~> 1.6.0.pre"])
  end
end

