# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{amaze-sns}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chee Yeo", "29 Steps UK"]
  s.date = %q{2010-05-04}
  s.description = %q{Ruby gem to interface with the Amazon Simple Notification Service}
  s.email = %q{info@29steps.co.uk}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "amaze-sns.gemspec",
     "amaze_sns.rb",
     "exceptions.rb",
     "helpers.rb",
     "request.rb",
     "spec/amaze_sns_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "topic.rb"
  ]
  s.homepage = %q{http://github.com/cheeyeo/Amazon-SNS-Ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby gem for Amazon Simple Notification Service SNS}
  s.test_files = [
    "spec/amaze_sns_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.9"])
      s.add_runtime_dependency(%q<em-http-request>, [">= 0.2.8"])
      s.add_runtime_dependency(%q<crack>, [">= 0.1.6"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
      s.add_dependency(%q<em-http-request>, [">= 0.2.8"])
      s.add_dependency(%q<crack>, [">= 0.1.6"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.9"])
    s.add_dependency(%q<em-http-request>, [">= 0.2.8"])
    s.add_dependency(%q<crack>, [">= 0.1.6"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

